/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  const resumeUrl = 'https://docs.google.com/document/d/1PbBYka9NNQ80eJZ_gqrUpP2o4D39pf4TlO2fBI441HA/edit?usp=sharing'
  const openInNewTab = (url) => {
    const newWindow = window.open(url, '_blank', 'noopener,noreferrer')
    if (newWindow) newWindow.opener = null
  }
  return (
    <div>
      <Head>
        <title>Mehdi Alouane - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet" />
      </Head>

      {/* header */}
      <div className='w-full h-16 bg-white border-b border-gray-300'>
        <h1 className='pt-4 pl-8 text-lg text-gray-900'>Nucleas</h1>
      </div>

      {/* Hero */}
      <div className='w-full h-96 bg-gray-100 font-sans'>
        <div className='w-full h-full flex justify-center'>
          <div className='mx-auto mt-36 text-gray-900 text-center'>
            <h1 className='text-6xl'>Mehdi Alouane</h1>
            <p className='text-left text-base mt-2 text-gray-600'>A self taught software engineer currently working @Trueface</p>
            <button onClick={() => openInNewTab(resumeUrl)} className='border hover:border-blue-400 bg-gray-300 border-gray-300 text-gray-800 px-4 text-base py-2 rounded mt-6 mr-2'>Resume</button>
            <button onClick={() => openInNewTab('mailto:meehdialouane@gmail.com')} className='border border-indigo-700 text-white bg-indigo-700 px-4 text-base py-2 rounded'>Get in touch</button>
          </div>
        </div>
      </div>
    </div>
  )
}
